### ISSUE TITLE
Możliwość dodania mapy, mimo locka założonego przez kogoś innego

### ISSUE THREAD

**Issue by mwarzec** [Delwing/arkadia-mapa#111]
/_mapup

  Arkadia Crowdmap Upload

  (1) Musisz miec uprawnienia do wrzucania map
  (2) Pamietaj aby po rozpoczeciu locka pobrac aktualna wersje mapy z serwera.
  (3) Twoja wersja: 0.99.0, wersja na serwerze: 0.99.0
  (4) Zaloz lock:
        - godzina
        - 2 godziny
        - 4 godziny
        - 8 godzin

(skrypty): Lock juz istnieje. Uzytkownik: felixd. Wazny do 22.12.2023, 21:15:41.

/zapisz_mape
(skrypty): Mapa zapisana
Masz zalozonego locka. Kliknij tutaj, aby zaktualizowac mape.
(skrypty): Mapa zapisana
(skrypty): Wysylam mape i tworze PR
(skrypty): Zdejmuje locka.
(skrypty): Nie mozna zdjac locka. Lock zalozony przez uzytkownika: felixd.

**Comment by Delwing** [comment]
Lock jest po to, żeby nie można było tego zrobić.

**Comment by Delwing** [comment]
Fixed.
