### ISSUE TITLE
/rysuj

### ISSUE THREAD

**Issue by mwarzec** [Delwing/arkadia-mapa#8]
Do kliknięciu w kolor lub symbol lokacji i po zmianie w mapie wywoływać funkcję odświeżenia mapy

updateMap()

aby zmiana była widoczna, bez konieczności wejścia/wyjścia z lokacji czy innej kombinacji.

**Comment by Delwing** [comment]
To raczej zgłoszenie do Mudleta, bo to powinno się dziać.
